# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('images', models.TextField()),
                ('cat', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
    ]
