# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
