# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserv', '0005_auto_20170202_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.ImageField(default='images/no-img.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mem_type',
            field=models.CharField(choices=[('0', 'UNPAID'), ('1', 'PAID'), ('2', 'CREDIT')], default='0', max_length=1),
        ),
    ]
