# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiserv', '0008_merge_20170202_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
