# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserv', '0011_auto_20170327_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_desc',
            field=models.CharField(max_length=80),
        ),
    ]
